config/routes.rb
Rails.application.routes.draw do
  # resources :answers
  resources :topics
  resources :questions do
    member do
      post :answer
    end
    # resources :answers, only: [:create]
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/question/:id', to: 'home#question', as: :home_question

  root to: "home#index"

  resources :followers, only: [] do
    member do
      post :follow_user
      post :follow_topic
    end
  end

end

app/models/question.rb
class Question < ApplicationRecord
  acts_as_followable
  belongs_to :user
  belongs_to :topic
  has_many :answers

  validates :topic_id, presence: true
  validates :user_id, presence: true
  validates :title, presence: true

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update, :destroy, :answer]

  # GET /questions
  # GET /questions.json
  def index
    @questions = current_user.my_questions.paginate(:page => params[:page])
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answer = @question.answers.new
    @answers = @question.answers
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user = current_user

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def answer
    @answer = Answer.new(answer_params)
    @answer.user = current_user
    @answer.question = @question

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :show }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:topic_id, :title, :description)
    end

    def answer_params
      params.require(:answer).permit(:answer)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      h2 = "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      ul
        - @question.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :topic_id
    = f.select :topic_id, Topic.pluck(:name, :id)
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/questions/edit.html.slim
h1 Editing question

== render 'form'

=> link_to 'Show', @question
'|
=< link_to 'Back', questions_path

app/views/questions/index.html.slim
h1 My Questions

table.table
  thead
    tr
      th User
      th Title
      th Description
      th
      th
      th

  tbody
    - @questions.each do |question|
      tr
        td = question.user_id
        td = question.title
        td = question.description
        td = link_to 'Show', question, class: 'question'
        td = link_to 'Edit', edit_question_path(question)
        td = link_to 'Destroy', question, data: { confirm: 'Are you sure?' }, method: :delete
    tr
      td[colspan="6"] = will_paginate @questions

br

= link_to 'New Question', new_question_path

app/views/questions/new.html.slim
h1 New question

== render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.slim
p#notice = notice

p
  strong User:
  = @question.user.try(:email)
p
  strong Title:
  = @question.title
p
  strong Description:
  = @question.description

- if current_user && @question.user_id == current_user.id
  = link_to 'Edit', edit_question_path(@question)
  '|
  = link_to 'Back', questions_path
= link_to 'Follow User', follow_user_follower_path(@question.user), method: :post, class: 'follow_user btn btn-primary'
br
br
= link_to 'Follow Topic', follow_question_follower_path(@question.user), method: :post, class: 'follow_topic btn btn-primary'