config/routes.rb
Rails.application.routes.draw do
  # resources :answers
  resources :topics
  resources :questions do
    member do
      post :answer
    end
    # resources :answers, only: [:create]
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/question/:id', to: 'home#question', as: :home_question

  root to: "home#index"

  resources :followers, only: [] do
    member do
      post :follow_user
      post :follow_topic
    end
  end

end

app/models/topic.rb
class Topic < ApplicationRecord
  acts_as_followable
  has_many :questions
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:user_id, :name)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.slim
= form_for @topic do |f|
  - if @topic.errors.any?
    #error_explanation
      h2 = "#{pluralize(@topic.errors.count, "error")} prohibited this topic from being saved:"
      ul
        - @topic.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/topics/edit.html.slim
h1 Editing topic

== render 'form'

=> link_to 'Show', @topic
'|
=< link_to 'Back', topics_path

app/views/topics/index.html.slim
h1 Listing topics

table
  thead
    tr
      th User
      th Name
      th
      th
      th

  tbody
    - @topics.each do |topic|
      tr
        td = topic.user_id
        td = topic.name
        td = link_to 'Show', topic
        td = link_to 'Edit', edit_topic_path(topic)
        td = link_to 'Destroy', topic, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Topic', new_topic_path

app/views/topics/new.html.slim
h1 New topic

== render 'form'

= link_to 'Back', topics_path

app/views/topics/show.html.slim
p#notice = notice

p
  strong User:
  = @topic.user_id
p
  strong Name:
  = @topic.name

=> link_to 'Edit', edit_topic_path(@topic)
'|
=< link_to 'Back', topics_path