config/routes.rb
Rails.application.routes.draw do
  # resources :answers
  resources :topics
  resources :questions do
    member do
      post :answer
    end
    # resources :answers, only: [:create]
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/question/:id', to: 'home#question', as: :home_question

  root to: "home#index"

  resources :followers, only: [] do
    member do
      post :follow_user
      post :follow_topic
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @questions = Question.limit(10)
  end

  def question
    @question = Question.find(params[:id])
    @answers = @question.answers
  rescue
    flash[:danger] = 'Resource is not found'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.slim
h1 All Questions

table.table
  thead
    tr
      th Title
      th Description
      th

  tbody
    - @questions.each do |question|
      tr
        td = question.title
        td = question.description
        td = link_to 'Show', home_question_path(question), class: 'question'
br

app/views/home/question.slim
p#notice = notice

p
  strong User:
  = @question.user.try(:email)
p
  strong Topic:
  = @question.topic.try(:name)
p
  strong Title:
  = @question.title
p
  strong Description:
  = @question.description

- if current_user
  h2 Post Answer
  = form_for :answer, url: answer_question_path(id: @question.id) do |f|
    = f.text_area :answer
    p
      = f.submit('Submit')

br
br
h2 Answers
- if @answers.any?
  table.table
    - @answers.each do |answer|
      tr
        td.answer=answer.answer

br
br
- if current_user
  - if @question.user_id == current_user.id
    = link_to 'Edit', edit_question_path(@question)
    '|
  br
  br
  = link_to 'Follow User', follow_user_follower_path(@question.user), method: :post, class: 'follow_user btn btn-primary'
  br
  br
  = link_to 'Follow Topic', follow_topic_follower_path(@question.topic), method: :post, class: 'follow_topic btn btn-primary'