config/routes.rb
Rails.application.routes.draw do
  # resources :answers
  resources :topics
  resources :questions do
    member do
      post :answer
    end
    # resources :answers, only: [:create]
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/question/:id', to: 'home#question', as: :home_question

  root to: "home#index"

  resources :followers, only: [] do
    member do
      post :follow_user
      post :follow_topic
    end
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :answer, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)
    @answer.user = current_user

    respond_to do |format|
      if @answer.save
        format.html { redirect_to questions_path(@answer.question), notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:question_id, :answer)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.slim
= form_for @answer do |f|
  - if @answer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
      ul
        - @answer.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :question_id
    = f.number_field :question_id
  .field
    = f.label :answer
    = f.text_field :answer
  .actions = f.submit

app/views/answers/edit.html.slim
h1 Editing answer

== render 'form'

=> link_to 'Show', @answer
'|
=< link_to 'Back', answers_path

app/views/answers/index.html.slim
h1 Listing answers

table
  thead
    tr
      th User
      th Question
      th Answer
      th
      th
      th

  tbody
    - @answers.each do |answer|
      tr
        td = answer.user_id
        td = answer.question_id
        td = answer.answer
        td = link_to 'Show', answer
        td = link_to 'Edit', edit_answer_path(answer)
        td = link_to 'Destroy', answer, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Answer', new_answer_path

app/views/answers/new.html.slim
h1 New answer

== render 'form'

= link_to 'Back', answers_path

app/views/answers/show.html.slim
p#notice = notice

p
  strong User:
  = @answer.user_id
p
  strong Question:
  = @answer.question_id
p
  strong Answer:
  = @answer.answer

=> link_to 'Edit', edit_answer_path(@answer)
'|
=< link_to 'Back', answers_path